layouts/partials/post.html
layouts/partials/user-profile.html

Added an avatar parameter that will allow custom avatar urls instead of only local images

allow custom avatar url

---

layouts/partials/user-profile.html

Some people don't want to show their email address.

Do not display if email is not set.

---

layouts/partials/user-profile.html

I changed it so that I can change it if another home page exists.

website URL can be changed

---

layouts/partials/user-profile.html

Hide github icon if config.toml doesn't have github

Hide github icon

---

layouts/partials/user-profile.html

https://github.com/MeiK2333/github-style/issues/12

fix issue #12

---

layouts/partials/head.html
layouts/partials/post.html
static/css/dark.css

Add dark style

---

README.md
archetypes/default.md
layouts/partials/extended_head.html
layouts/partials/head.html

- Add meta tags for social media
- Add keywords to posts and home page

feat(seo): Add meta tags & keywords

---

archetypes/default.md
layouts/partials/head.html
layouts/partials/post.html

- Fixed some typos
- Add a site property to disable dark mode

Fix miscellaneous typos

---

README.md
layouts/partials/overview.html
layouts/partials/post.html
layouts/partials/posts.html

bug fix related to these two issues:
https://github.com/MeiK2333/github-style/issues/25
https://github.com/MeiK2333/github-style/issues/42

fix https://github.com/MeiK2333/github-style/issues/25

---

static/js/contributions.js

fix an issue that `monthly()` does not consider years (#45 )

fix https://github.com/MeiK2333/github-style/issues/45

---

layouts/partials/menus.html

fix: 编辑器自动换行导致的错误

---

layouts/partials/post.html
static/css/dark.css
static/css/github-style.css
static/css/light.css

This feature is (I think) very useful for navigating large posts. Similar to what Github does for Markdown/Org-mode files.
Addresses #https://github.com/MeiK2333/github-style/issues/71
Demo:
https://user-images.githubusercontent.com/15933322/126865896-dbb95aa3-07f2-40ee-b085-eba367fd3a26.mp4

Feature: Table of Contents + Fixed Header

---

layouts/404.html

fix(layouts): fix 404 page in dark mode

---

layouts/partials/script.html

Use fastly.jsdelivr.net instead of cdn.jsdelivr.net since the latter is blocked in China.

Use fastly.jsdelivr.net

---

README.md
layouts/partials/posts.html
layouts/partials/script.html
layouts/partials/tags.html

feat: Add tag-based classification and Support MathJax now

---

README.md
layouts/shortcodes/details.html

feat: support collapsible block

feat: support collapsible block

---

layouts/partials/user-profile.html

perf: adjust avatar position when in different box

perf: adjust avatar position when in different box

---

README.md
config.template.toml
layouts/partials/extended_head.html

Which then matches the 404 page.

Use Hugo built-in GA

---

layouts/partials/script.html

update: KaTeX version

---

layouts/partials/user-profile.html
static/js/theme-mode.js

no twitterIconElement will raise error when switched theme.
Reproduce:
disable twitter/X icon in config.toml and switch theme.

fix: no twitterIconElement raise error

---

README.md
config.template.toml
layouts/_default/baseof.html
layouts/_default/index.json
layouts/_default/list.html
layouts/_default/single.html
layouts/partials/header.html
layouts/partials/script.html
layouts/partials/search.html
static/js/search.js

通过 `Fuse.js` 进行本地搜索。
ref: https://github.com/HugoBlox/hugo-blox-builder/ and https://github.com/brunocechet/Fuse.js-with-highlight/

feat: allow local search

---

layouts/partials/menus.html
layouts/partials/mobile-menus.html

fix: use hugo 's api instead of static to  splice url

---

README.md
layouts/partials/head.html

Adds _custom_css_ and _custom_js_ support to add headers in _layouts/partials/head.html_

Adds support for custom_css and custom_js
